### ISSUE TITLE
Clamp needle position range to stop the tip going outside the box

### ISSUE THREAD

**Issue by colinl** [colinl/node-red-dashboard-2-ui-gauge-classic#8]
Prevent such as this example, using a 3x2 widget size and 220 deg sweep.

![image](https://github.com/user-attachments/assets/73e3673d-3b74-44ae-9684-afcaa0b8f573)

**Comment by colinl** [comment]
Fixed by v1.2.0.  The needle position is now limited so as to prevent it being truncated as in the example shown

**Comment by mcdonaldajr** [comment]
Tested OK on Safari on Mac and iPhone. Little black dots signifying end stops might be nice, but that's just being picky!

**Comment by colinl** [comment]
Thanks for testing

> Little black dots signifying end stops might be nice

I had thought of that.  Maybe I will look at it one rainy afternoon.  Or PRs are always welcome.
